inherit_from:
  - https://raw.githubusercontent.com/rails/rails/master/.rubocop.yml

AllCops:
  Exclude:
    - activerecord-ignored_columns.gemspec
    - test/dummy/**/*

Metrics/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: normal
