language: ruby
sudo: false
rvm:
  - 2.3.8
  - 2.4.6
gemfile:
  - gemfiles/activerecord_4_1.gemfile
  - gemfiles/activerecord_4_2.gemfile
  - gemfiles/activerecord_5_0.gemfile
matrix:
  exclude:
    - rvm: 2.4.6
      gemfile: gemfiles/activerecord_4_1.gemfile
branches:
  only:
    - master
before_install:
  - gem update --system --no-doc
